### ISSUE TITLE
Invalid string length when hash is called on a particular large object

### ISSUE THREAD

**Issue by charlesritchea** [arthurfiorette/tinylibs#241]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

1.3.0

### Description

We just upgraded axios to 1.x and your axios-cache-interceptor. One of our PATCH calls takes in a ~32k object as the body, but we are getting "Invalid string length" from the JSON.stringify at the end of the object-code hash function

### Steps to Reproduce

I'm waiting to get permissions to send the JSON that triggers this, it's customer data so you know how that goes.

PS I tried replacing all letters with a and all numbers with 1, but it failed to reproduce in that case, making me think this is all about the complexity of the object send to JSON.stringify. chunking the object in some way should fix this. I've seen other complaints about JSON.stringify where they chunked objects in an array, so I'm guessing you'd have to do the same thing with objects

### Expected Behavior

Invalid string length is not thrown, a hash int is returned

**Comment by arthurfiorette** [comment]
Hey @charlesritchea, I'm not sure if it will be possible to cache such huge objects, however I'll take a deeper look at it as soon as I can, you're up to try fixing it in a PR?

**Comment by charlesritchea** [comment]
@charlesritchea Sorry, I'm too busy, I mean maybe if I become obsessed lol. We also tried to disable the cache for just this request, because it's probably the only one with such large payloads, but the hash function was still called

**Comment by charlesritchea** [comment]
Would you be able to confirm how to disable the cache for an axios.patch call?, we tried passing `{ cache: false }` as the last parameter, is that not correct?
