### ISSUE TITLE
Bug: Runtime Type Error in Cache-Parser Where Header Token Contains no ,

### ISSUE THREAD

**Issue by nagilson** [arthurfiorette/tinylibs#301]
### What happened?

This code: https://github.com/arthurfiorette/tinylibs/blob/main/packages/cache-parser/src/util.ts#L18 , which this library seems to depend on, is failing at runtime for us in a rare number of cases.

(I was very relieved to see you manage both libraries, so thank you for the work you do :). )

My very quick glance is the problem is the code seems to rely on the fact that , is in the header of the string that is passed to it. I dont think that assumption can always hold true, so sometimes the token ends up being null or a type other than string, so when .split is called on it, there becomes an uncaught runtime error. The split on line 22 is the culprit.

I don't know much more of the context of the code here and there might be some other reason, but that is my suspicion.
Example is https://github.com/dotnet/vscode-dotnet-runtime/issues/1734.
I don't have a repro, this info is garnered from customers.
 
It is causing some issues for us over in VS Code land and it is one of our highest causes of failure, causing roughly .01% out of several million customers to fail, with a high report rate on mac os sonoma silicon m1. 

### axios-cache-interceptor version

^1.0.1

### Node / Browser Version

16

### Axios Version

^1.3.4

### What storage is being used

Memory Storage

### Relevant debugging log output

```js
Failed: n[r].split is not a function. Aborting. Stack: TypeError: n[r].split is not a function
    at /usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/esm|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\cache-parser\dist\index.mjs:1:425
    at parse (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/esm|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\cache-parser\dist\index.mjs:1:327)
    at Function.headerInterpreter (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios-cache-interceptor\dist\index.cjs:2:1324)
    at n (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios-cache-interceptor\dist\index.cjs:2:5445)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Pt.request (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios\dist\node\axios.cjs:3872:7)
    at Pt.request (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios\dist\node\axios.cjs:3877:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by nagilson** [comment]
Hm, that's a good theory. I checked and it looks like it's coming from `lib.es2015.symbol.wellknown.ts`, so unfortunately probably not.

What I am suspicious about is that my minified code is identical to yours, and despite the fact that the callstack aligns with the `.split` in my file, the error is on `n[r].split`, but the split on the character line is `n = r[t].split()`. I don't know why that'd be the case. If you have an idea, or there is more I can do to get the header string for you based on the above, please let me know.

Based on the Javascript spec, this should not be possible. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#:~:text=Note%3A%20%22%22.split(%22%22)%20is%20therefore%20the%20only%20way%20to%20produce%20an%20empty%20array%20when%20a%20string%20is%20passed%20as%20separator%20and%20limit%20is%20not%200. Split would never return an empty array, and you loop for token in tokens anyway. Token would have to be a non string type, but I dont see in the spec how that is possible with string.

**Comment by nagilson** [comment]
I'm going to double check with our customer to see if their string split method has been modified. (Note this has happened more than a few times, so I would not resolve it to a bit flip...)

**Comment by nagilson** [comment]
Another thought: Typescript checks are only at compile time. Does any of your code edit things at runtime?
I have an idea to collect the header from the user. If that does not work, I guess we'll need to prioritize and see if we have time to try some obscure linux distros and repro it.

**Comment by arthurfiorette** [comment]
I actually have no clue on how to solve this issue... I build the project in my machine and the output seems to have changed, probably because the bundler have been updated since the latest `cache-parser` release.

![image](https://github.com/arthurfiorette/tinylibs/assets/47537704/cc5f7ef3-7b4a-4371-bb50-f5d420b66d9f)

I could try to release a new version with this different bundle and see if this error stops...

**Comment by arthurfiorette** [comment]
> Does any of your code edit variables at runtime in places it would not do so at compile time?

Everything gets executed the same way it's written...

**Comment by arthurfiorette** [comment]
Hey @nagilson any updates?

**Comment by nagilson** [comment]
Apologies, I was on vacation. The thing I can confirm is that the string split method was not modified. I don't have any further insights at the moment. So I would appreciate you giving it a go with the bundler to see if that fixes the issue. 

Thanks for your continued investment in my issue.

**Comment by arthurfiorette** [comment]
[Just released v1.2.5](https://github.com/arthurfiorette/tinylibs/actions/runs/9177447744/job/25235057333). Let's see if it fixes this weird problem :/

**Comment by arthurfiorette** [comment]
[axios-cache-interceptor v1.5.3](https://github.com/arthurfiorette/axios-cache-interceptor/releases/tag/v1.5.3) was released.

**Comment by nagilson** [comment]
Thanks! Ill get the update in our next release and see if it fixes it :)

**Comment by nagilson** [comment]
We just released our new version with the patch. In a few days we should have enough data to see whether or not this change worked!

**Comment by nagilson** [comment]
Hi @arthurfiorette, thank you so much for your responsiveness with this issue. :)

While it would be good to have more days of data to confirm, we have not seen this error hit a single time in the span of about a day, where it used to be our most prominent error. We have quite a large data set already. Given this, I would conclude that it's been resolved! 🥳

**Comment by nagilson** [comment]
Btw, this seemed to mostly be a linux error, it especially happened on more obscure distros like Pop OS. Maybe that will be useful to know if there is a bundler issue in the future....
